### ISSUE TITLE
Can only set the settings for the top data instrument - is this intended?

### ISSUE THREAD

**Issue by harpsicord86** [uwctri/DefaultFormStatus#1]
Hi @aanunez 

I'm afraid that I may have found a bug with your module... its functionality seems to be limited only to whatever is at the top of the data instrument list. I can see that the settings do appear on all instruments within the Online Designer but unless the form is at the top, the settings are not applied. Is that intentional?

**Comment by harpsicord86** [comment]
Just to add to any investigations, I have taken a look at my saved configuration and this is what it shows:

`{
    "demographic_data": {"note":"","select":"2","hide":true,"save":false},
    "interview_consent_form":[],
    "mailout_log":[],
    "returned_items_log":[],
    "optout_request":[]
}`

It looks as though the process which writes the json for this config works for the top DI but none other after that. I can manipulate the json with the settings I want which is a workaround at least....

**Comment by aanunez** [comment]
Hey Steve. Just wanted to let you know I plan on looking at this, I've been out sick for the past two days.

**Comment by aanunez** [comment]
Hey @harpsicord86 , I just looked at this and I believe I've resolved it with commit 14, but I'm not sure why the issue would only impact instruments past the first. Please update when you are able to (should be available from Vanderbilt in a day or two) and let me know if the issue is resolved.

**Comment by harpsicord86** [comment]
Hey @aanunez,

Thanks for getting back to me... hope you are feeling better! I've updated the module and tested it and I'm happy to report that it's working as intended. Thanks for getting on it so quickly -  will close this issue
